### ISSUE TITLE
Error in set api token

### ISSUE THREAD

**Issue by gullitmiranda** [timbooo/traktforalfred#5]
Starting debug for 'Trakt for Alfred'

```log
[INFO: alfred.workflow.input.keyword] Processing output 'alfred.workflow.action.script' with arg '6E97A0B6'
[ERROR: alfred.workflow.action.script] Traceback (most recent call last):
  File "traktforalfred.py", line 5, in <module>
    from traktapi import TraktAPI
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.2BD81DDB-B946-42DF-A068-34B36A1FDD4C/traktapi.py", line 5, in <module>
    from trakt import Trakt
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.2BD81DDB-B946-42DF-A068-34B36A1FDD4C/trakt/__init__.py", line 3, in <module>
    from trakt.client import TraktClient, __version__
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.2BD81DDB-B946-42DF-A068-34B36A1FDD4C/trakt/client.py", line 1, in <module>
    from trakt.core.configuration import ConfigurationManager
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.2BD81DDB-B946-42DF-A068-34B36A1FDD4C/trakt/core/configuration.py", line 1, in <module>
    from trakt.core.context_collection import ContextCollection
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.2BD81DDB-B946-42DF-A068-34B36A1FDD4C/trakt/core/context_collection.py", line 1, in <module>
    from trakt.core.helpers import synchronized
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.2BD81DDB-B946-42DF-A068-34B36A1FDD4C/trakt/core/helpers.py", line 1, in <module>
    import arrow
ImportError: No module named arrow
[INFO: alfred.workflow.action.script] Processing output 'alfred.workflow.output.notification' with arg ''
```

**Comment by timbooo** [comment]
Looks like this has been fixed in trakt.py 2.4.1 (https://github.com/fuzeman/trakt.py/releases/tag/2.4.1). The workflow is currently using 2.4.0. Will update/test as soon as I will find some time.

**Comment by timbooo** [comment]
Updated trakt.py dependency. Please try again!

**Comment by gullitmiranda** [comment]
still does not working:

```log
[INFO: alfred.workflow.input.keyword] Processing output 'alfred.workflow.action.script' with arg '00000000'
[ERROR: alfred.workflow.action.script] Traceback (most recent call last):
  File "traktforalfred.py", line 6, in <module>
    from traktapi import TraktAPI
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.FE39286F-42BE-4325-8B7C-F84AAB05DD40/traktapi.py", line 5, in <module>
    from trakt import Trakt
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.FE39286F-42BE-4325-8B7C-F84AAB05DD40/trakt/__init__.py", line 3, in <module>
    from trakt.client import TraktClient
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.FE39286F-42BE-4325-8B7C-F84AAB05DD40/trakt/client.py", line 3, in <module>
    from trakt.core.http import HttpClient
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.FE39286F-42BE-4325-8B7C-F84AAB05DD40/trakt/core/http.py", line 5, in <module>
    from trakt.core.request import TraktRequest
  File "/Users/gmmaster/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.FE39286F-42BE-4325-8B7C-F84AAB05DD40/trakt/core/request.py", line 1, in <module>
    from requests import Request
ImportError: No module named requests
[INFO: alfred.workflow.action.script] Processing output 'alfred.workflow.output.notification' with arg ''
```

**Comment by der-tkw** [comment]
I hope that I fixed the dependency issues now. Tested on another El Capitan. Please try the new workflow.

**Comment by gullitmiranda** [comment]
Now works. :smiley: 
I intend to make a small contribution related to get token,
